
ALTER PROCEDURE "EW_PRD_TEST"._USP_CALLLAYOUT_CONFIRMBOOKING_SEA_AIR(
	in DTYPE NVARCHAR(250)
	,in par1 NVARCHAR(250)
	,in par2 NVARCHAR(250)
	,in par3 NVARCHAR(250)
	,in par4 NVARCHAR(250)
	,in par5 NVARCHAR(250)
)
AS
BEGIN
	IF :par1 = 'BookingSheetInformationSeaAir' THEN 
		SELECT 
			 B."Name" AS JOBTYPE
			,C."descript"||' - '|| CC."descript" AS ROUTE
			,D."SlpName" AS SALENAME
			,CASE WHEN A."CreateDate"<'2024-03-06' THEN
					 	CASE WHEN (SELECT COUNT(*) FROM EW_PRD_TEST."@CON_BOOKING_S_A" WHERE "U_BOOKINGID"=A."DocEntry" AND "Status"='O' AND "CreateDate">='2024-03-06')=0 THEN
					 		IFNULL(B."U_JOBTYPE",'')||(SELECT TO_VARCHAR(A."U_BOOKINGDATE",'YYMM')
						 	||CASE WHEN LENGTH(IFNULL(A."DocEntry",1))>=4 
								THEN 
									CAST(A."DocEntry" AS NVARCHAR(100))
								ELSE 
									CASE WHEN LENGTH(IFNULL(A."DocEntry",1))=1
										THEN
									  		'000'||CAST(IFNULL(A."DocEntry",1) AS NVARCHAR(100))
									  	WHEN LENGTH(A."DocEntry")=2 THEN
									  		'00'||CAST(A."DocEntry" AS NVARCHAR(100))
									  	WHEN LENGTH(A."DocEntry")=3 THEN
									  		'0'||CAST(A."DocEntry" AS NVARCHAR(100))
									  	END
							END FROM dummy)
					 	ELSE
					 		(SELECT "NAME"
					 			FROM EW_PRD_TEST."@CON_BOOKING_S_A" AS T0
					 			LEFT JOIN EW_PRD_TEST."OPMG" AS T1 ON T1."AbsEntry"=T0."U_PROJECTMANAGEMENTID"
					 		 WHERE T0."U_BOOKINGID"=A."DocEntry" AND T0."Status"='O' AND T0."CreateDate">='2024-03-06') 
					 	END
					  ELSE IFNULL(B."U_JOBTYPE",'')||A."DocNum" END AS JOBNO
			,E."ListName" AS PRICELIST
			,A."Remark" AS REMARK
			,AA."DocEntry" AS DOCENTRY
			,G."firstName" || ' ' || G."lastName" AS USERNAME
			,TO_VARCHAR(A."U_LOADINGDATE",'DD-MONTH-YYYY') AS LOADINGDATE
			,A."U_SPECIALREQUEST" SPECIALREQUEST
		FROM EW_PRD_TEST."@BOOKING_SEA_AIR" AS A
		LEFT JOIN EW_PRD_TEST."@CON_BOOKING_S_A" AS AA ON AA."DocEntry"=:par2
		LEFT JOIN EW_PRD_TEST."@TBJOBTYPE" AS B ON A."U_IMPORTTYPE"=B."Code"
		LEFT JOIN EW_PRD_TEST."OTER" AS C ON C."territryID"=A."U_ORIGIN" --ORIGIN
		LEFT JOIN EW_PRD_TEST."OTER" AS CC ON CC."territryID"=A."U_DESTINATION" --DESTINATION
		LEFT JOIN EW_PRD_TEST."@TBJOBTYPE" AS CCC ON CCC."Code"=A."U_IMPORTTYPE" -- Get JobSeries
		LEFT JOIN EW_PRD_TEST."OSLP" AS D ON D."SlpCode"=A."U_SALEEMPLOYEE"
		LEFT JOIN EW_PRD_TEST."OPLN" AS E ON TO_VARCHAR(E."ListNum")=IFNULL(AA."U_PRICELIST",'')
		LEFT JOIN EW_PRD_TEST."@TBUSER" AS F ON F."Code"=A."U_CreateBy"
		LEFT JOIN EW_PRD_TEST."OHEM" AS G ON G."empID"=F."U_EMPLOYEEID"
		WHERE A."U_CONFIRMBOOKINGSHEETID"=:par2;
	ELSE IF	:par1='GetCONSIGNEESeaAir' THEN
		SELECT 
			B."CardName" AS CONSIGNEE 
		FROM EW_PRD_TEST."@BOOKING_SEA_AIR" AS AA
		LEFT JOIN EW_PRD_TEST."@TBCONSIGNEE_SEA_AIR" AS A ON AA."DocEntry"=A."DocEntry"
		LEFT JOIN EW_PRD_TEST."OCRD" AS B ON B."CardCode"=A."U_CONSIGNEE"
		WHERE AA."U_CONFIRMBOOKINGSHEETID"=:par2;
	ELSE IF :par1 = 'GetBorderBookingSheetSeaAir' THEN 
		SELECT 
			 IFNULL(C."Code",'') AS CODE
			,IFNULL(C."Name",'') AS NAME
		FROM EW_PRD_TEST."@BOOKING_SEA_AIR" AS A
		LEFT JOIN EW_PRD_TEST."@TB_THAI_B_SEA_AIR" AS B ON A."DocEntry"=B."DocEntry"
		LEFT JOIN EW_PRD_TEST."@TBTHAIBORDER" AS C ON C."Code"=B."U_THAIBORDER"
		WHERE A."U_CONFIRMBOOKINGSHEETID"=:par2;
	ELSE IF :par1 = 'GetPLACEOFLOADINGSeaAir' THEN 
		SELECT 
			B."Name"||', '||B."U_COUNTRY" AS PLACELOADING
		FROM EW_PRD_TEST."@BOOKING_SEA_AIR" AS AA
		LEFT JOIN EW_PRD_TEST."@TB_POL_SEA_AIR" AS A ON A."DocEntry"=AA."DocEntry"
		LEFT JOIN EW_PRD_TEST."@TBPLACEOFLOADING" AS B ON B."Code"=A."U_PLACEOFLOADING"			
		WHERE AA."U_CONFIRMBOOKINGSHEETID"=:par2;
	ELSE IF	:par1='GetSHIPPERSeaAir' THEN
		SELECT 
			B."CardName" AS SHIPPER 
		FROM EW_PRD_TEST."@BOOKING_SEA_AIR" AS AA
		LEFT JOIN EW_PRD_TEST."@TBSHIPPER_SEA_AIR" AS A ON A."DocEntry"=AA."DocEntry"
		LEFT JOIN EW_PRD_TEST."OCRD" AS B ON B."CardCode"=A."U_SHIPPER"
		WHERE AA."U_CONFIRMBOOKINGSHEETID"=:par2;
	ELSE IF	:par1='GetPLACEOFDELIVERYSeaAir' THEN
		SELECT 
			B."Name"||', '||B."U_COUNTRY" AS PLACEOFDELIVERY 
		FROM EW_PRD_TEST."@BOOKING_SEA_AIR" AS AA
		LEFT JOIN EW_PRD_TEST."@TB_POD_SEA_AIR" AS A ON AA."DocEntry"=A."DocEntry"
		LEFT JOIN EW_PRD_TEST."@TBPLACEOFDELIVERY" AS B ON B."Code"=A."U_PLACEOFDELIVERY"
		WHERE AA."U_CONFIRMBOOKINGSHEETID"=:par2;
	ELSE IF :par1='GetListOfContainerInformationSeaAir' THEN
		SELECT 
			 A."U_TYPE" AS "TYPE"
			,A."U_CONTAINERTYPE" AS CONTAINERTYPE
			,A."U_CONTAINERNO" AS CONTAINERNO
			,A."U_OWNER" AS OWNER
			,A."U_GROSSWEIGHT" AS GROSSWEIGHT
			,A."U_YARD" AS YARD
			,A."U_FCL_LCL" AS FCL_LCL
			,A."U_LOLO_UNLOADING" AS LOLO_UNLOADING
			,A."U_TRUCKPROVINCE" AS TRUCKPROVINCE
			,A."U_TRUCKPLATENO" AS TRUCKPLATENO
			,A."U_TRUCKTYPE" AS TRUCKTYPE
			,A."U_BRAND" AS BRAND
			,A."U_COLOR" AS COLOR
			,A."U_TRAILERPROVINCE" AS TRAILERPROVINCE
			,A."U_TRAILERPLATE" AS TRAILERPLATE
			,A."U_TRAILERTYPE" AS TRAILERTYPE
			,C."firstName" ||' '|| C."lastName" AS DriverName1
			,C."mobile" AS TPNO1
			,C."govID" AS IDCARD1
			,C."U_DriverID" AS DRIVERLICENSE1
			,CC."firstName" ||' '|| C."lastName" AS DriverName2
			,CC."mobile" AS TPNO2
			,CC."govID" AS IDCARD2
			,CC."U_DriverID" AS DRIVERLICENSE2
			,E."CardName" AS VENDOR
			,A."U_TRUCKCOSTTHB" AS TRUCKCOSTTHB
			,A."U_SEALNO1" AS SEALNO1
			,A."U_SEALNO2" AS SEALNO2
		FROM EW_PRD_TEST."@TRUCK_INFO_S_A" AS A 
		LEFT JOIN EW_PRD_TEST."OLCT" AS B ON CAST(B."Code" AS VARCHAR(255))=A."U_TRUCKPROVINCE"
		LEFT JOIN EW_PRD_TEST."OHEM" AS C ON C."empID"=A."U_DRIVER1"
		LEFT JOIN EW_PRD_TEST."OHEM" AS CC ON CC."empID"=A."U_DRIVER2"
		LEFT JOIN EW_PRD_TEST."OITM" AS D ON D."ItemCode"=A."U_TRUCKPLATENO"
		LEFT JOIN EW_PRD_TEST."OCRD" AS E ON E."CardCode"=A."U_VENDORCODE" --Vendor
			WHERE A."DocEntry"=:par2;
	ELSE IF :par1='GetListCommoditiesSeaAir' THEN
		SELECT 
			A."U_Invoice" AS INVOICE
		FROM EW_PRD_TEST."@COMMODITY_SEA_AIR" AS A 
		LEFT JOIN EW_PRD_TEST."@CON_BOOKING_S_A" AS B ON B."U_BOOKINGID"=A."DocEntry"
		WHERE B."DocEntry"=:par2;
	ELSE IF :par1='GetVolumeBookingSheetByDocEntrySeaAir' THEN
		SELECT 
			 A."U_Qty" AS QTY
			,A."U_ContainerType" AS VOLUMECODE
			,A."U_ContainerType" AS VOLUME
		FROM EW_PRD_TEST."@TB_CON_S_A" AS A
		LEFT JOIN EW_PRD_TEST."@CON_BOOKING_S_A" AS D ON D."U_BOOKINGID"=A."DocEntry"
		WHERE D."DocEntry"=:par2;
	END IF;	
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
END;
