--CALL "EW_PRD"._USP_CALLLAYOUT_EWLAYOUTS ('GetDetailAdvancePaymentByDocEntryLines','75','','','','')
--
ALTER PROCEDURE "EW_PRD"._USP_CALLLAYOUT_EWLAYOUTS(
	in DTYPE NVARCHAR(250)
	,in par1 NVARCHAR(250)
	,in par2 NVARCHAR(250)
	,in par3 NVARCHAR(250)
	,in par4 NVARCHAR(250)
	,in par5 NVARCHAR(250)
)
AS
BEGIN
	
	IF :DTYPE = 'SALESQUOTATIONLAYOUT' THEN 
		SELECT DISTINCT
			 A."CardCode" AS CARDCODE
			,A."DocNum" AS DOCNUM 
			,A."CardName" AS CARDNAME
			,A."NumAtCard" AS REFNO
			,A."U_ATTN" AS ATTN
			,TO_VARCHAR(A."DocDate",'DD/MM/YYYY') AS DOCDATE
			,A."U_EMAIL" AS EMAIL
			,TO_VARCHAR(A."DocDueDate",'DD/MM/YYYY') AS VALIDITY
			,A."U_TEL" AS TEL
			,B."PymntGroup" AS CREDITTERM
			,C."Name" AS SERVICE
			,AA."ItemCode" AS ITEMCODE
			,AA."Dscription" AS ITEMNAME
			/*,CASE WHEN AA."U_TYPE"='TRUCK' THEN
				(SELECT "descript" FROM EW_PRD."OTER" WHERE "territryID"=A."U_ORIGIN")
			ELSE
				''
			END AS ORIGIN */
			,(SELECT "descript" FROM EW_PRD."OTER" WHERE "territryID"=A."U_ORIGIN") AS ORIGIN
			/*,CASE WHEN AA."U_TYPE"='TRUCK' THEN
				(SELECT "descript" FROM EW_PRD."OTER" WHERE "territryID"=A."U_DESTINATION")
			ELSE
				''
			END AS DESTINATION */
			,(SELECT "descript" FROM EW_PRD."OTER" WHERE "territryID"=A."U_DESTINATION") AS DESTINATION
			,AA."LineTotal" AS TOTAL
			,IFNULL(AA."U_Remark",'') AS REMARKSLINE
			,IFNULL(A."Comments",'') AS REMARK
		FROM EW_PRD."OQUT" AS A
		LEFT JOIN EW_PRD."QUT1" AS AA ON A."DocEntry"=AA."DocEntry"
		LEFT JOIN EW_PRD."OCTG" AS B ON A."GroupNum"=B."GroupNum"
		LEFT JOIN EW_PRD."@TBSERVICE" AS C ON A."U_SERVICE"=C."Code"
		WHERE A."DocEntry"=:par1 ORDER BY DESTINATION DESC;
	ELSE IF :DTYPE='BOOKINGSHEET_LAYOUT' THEN
			SELECT 
				 A."DocEntry" AS DOCENTRY
				,A."DocEntry" AS BOOKINGID
				,A."U_EWSeries"||A."U_JOBNO" AS JOBNO
				,TO_VARCHAR(A."U_BOOKINGDATE",'DD/MM/YYYY') AS BOOKINGDATE
				,B."descript"||'-'||BB."descript" AS ROUTE
				,IFNULL(C."SlpName",'') AS SALEEMPLOYEE
				,D."Name" AS JOBTYPE
				,E."Name" AS SERVICETYPE
				,A."U_GOODSDESCRIPTION" AS GOODSDESCRIPTION
				,A."U_TOTALPACKAGE" AS TOTALPACKAGE				
				,IFNULL(TO_DECIMAL(A."U_NETWEIGHT",16,2),0) AS NETWEIGHT
				,IFNULL(TO_DECIMAL(A."U_GROSSWEIGHT",16,2),0) AS GROSSWEIGHT
				,TO_VARCHAR(A."U_LOADINGDATE",'DD/MM/YYYY') AS LOADINGDATE
				,TO_VARCHAR(A."U_CROSSBORDERDATE",'DD/MM/YYYY') AS CROSSBORDERDATE
				,TO_VARCHAR(A."U_ETAREQUIREMENT",'DD/MM/YYYY') AS ETAREQUIREMENT
				,F."Descr" AS "LOLOYARDORUNLOADING"
				,G."Descr" AS "LCLORFCL"
				,H."Descr" AS "CYORCFS"
				,B."descript" AS ORIGIN
				,B."descript" AS DESTINATION				
				,A."Remark" REMARK
				,A."U_SPECIALREQUEST" AS SPECIALREQUEST
				,I."U_NAME" AS USERNAME
				,I."USER_CODE" AS USERCODE
			FROM EW_PRD."@BOOKINGSHEET" AS A 
			LEFT JOIN EW_PRD."OTER" AS B ON A."U_ORIGIN"=B."territryID" --ORIGIN
			LEFT JOIN EW_PRD."OTER" AS BB ON BB."territryID"=A."U_DESTINATION" --DESTINATION
			LEFT JOIN EW_PRD."OSLP" AS C ON C."SlpCode"=A."U_SALEEMPLOYEE"
			LEFT JOIN EW_PRD."@TBJOBTYPE" AS D ON D."Code"=A."U_IMPORTTYPE"
			LEFT JOIN EW_PRD."@TBSERVICETYPE"AS E ON E."Code"=A."U_SERVICETYPE"
			LEFT JOIN EW_PRD."UFD1" AS F ON F."FieldID"='18' AND F."FldValue"=A."U_LOLOYARDORUNLOADING" AND F."TableID"='@BOOKINGSHEET' --LOLOYARD/UNLOADING
			LEFT JOIN EW_PRD."UFD1" AS G ON G."FieldID"='21' AND G."FldValue"=A."U_LCLORFCL" AND G."TableID"='@BOOKINGSHEET' --LCL/FCL
			LEFT JOIN EW_PRD."UFD1" AS H ON H."FieldID"='22' AND H."FldValue"=A."U_CYORCFS" AND H."TableID"='@BOOKINGSHEET' --CY/CFS
			LEFT JOIN EW_PRD."OUSR" AS I ON I."USERID"=A."U_UserCreate" -- Get User Name
			WHERE A."DocEntry"=:par1; --:par1;--
	ELSE IF :DTYPE='BOOKINGSHEET_SHIPPER_LAYOUT' THEN
			SELECT 
				B."CardName" AS SHIPPER 
			FROM EW_PRD."@TBSHIPPER" AS A 
			LEFT JOIN EW_PRD."OCRD" AS B ON B."CardCode"=A."U_SHIPPER"
			WHERE A."DocEntry"=:par1;
			/*UNION ALL
			SELECT 
				B."CardName" AS SHIPPER 
			FROM EW_PRD."@TBSHIPPER" AS A 
			LEFT JOIN EW_PRD."OCRD" AS B ON B."CardCode"=A."U_SHIPPER"
			WHERE A."DocEntry"=54;*/
	ELSE IF :DTYPE='BOOKINGSHEET_CONSIGNEE_LAYOUT' THEN
			SELECT 
				B."CardName" AS CONSIGNEE 
			FROM EW_PRD."@TBCONSIGNEE" AS A 
			LEFT JOIN EW_PRD."OCRD" AS B ON B."CardCode"=A."U_CONSIGNEE"
			WHERE A."DocEntry"=:par1;
	ELSE IF :DTYPE='BOOKINGSHEET_SALESQUOTATION_LAYOUT' THEN
			SELECT 
				 B."DocNum" AS DOCNUM
				,B."CardName" AS CUSTOMERNAME 
			FROM EW_PRD."@TBSALESQUOTATION" AS A 
			LEFT JOIN EW_PRD."OQUT" AS B ON A."U_DOCENTRY"=B."DocEntry"
			WHERE A."DocEntry"=:par1;
	ELSE IF :DTYPE='BOOKINGSHEET_COMMODITY_LAYOUT' THEN
			SELECT 
				A."U_INVOICE" AS INVOICE 
			FROM EW_PRD."@COMMODITY" AS A 
			WHERE A."DocEntry"=:par1;
	ELSE IF :DTYPE='BOOKINGSHEET_OVERSEATRUCKER_LAYOUT' THEN
	 	SELECT
			 B."CardName" AS OVERSEATRUCKERCODE 
		FROM EW_PRD."@TBOVERSEATRUCKER" AS A 
		LEFT JOIN EW_PRD."OCRD" AS B ON B."CardCode"=A."U_OVERSEATRUCKERCODE" 
		WHERE A."DocEntry"=:par1;
	ELSE IF :DTYPE='BOOKINGSHEET_PLACEOFLOADING_LAYOUT' THEN
			SELECT 
				B."Name"||', '||B."U_COUNTRY" AS PLACELOADING
			FROM EW_PRD."@PLACEOFLOADING" AS A 
			LEFT JOIN EW_PRD."@TBPLACEOFLOADING" AS B ON B."Code"=A."U_PLACELOADING"
			WHERE A."DocEntry"=:par1;
	ELSE IF :DTYPE='BOOKINGSHEET_PLACEOFDELIVERY_LAYOUT' THEN
			SELECT 
				B."Name"||', '||B."U_COUNTRY" AS PLACEOFDELIVERY 
			FROM EW_PRD."@PLACEOFDELIVERY" AS A 
			LEFT JOIN EW_PRD."@TBPLACEOFDELIVERY" AS B ON B."Code"=A."U_PLACEDELIVERY"
			WHERE A."DocEntry"=:par1;
	ELSE IF :DTYPE='BOOKINGSHEET_THAIFORWARDER__LAYOUT' THEN
			SELECT 
				B."CardName" AS THAIFORWARDER 
			FROM EW_PRD."@THAIFORWARDER" AS A 
			LEFT JOIN EW_PRD."OCRD" AS B ON B."CardCode"=A."U_THAIFORWARDER"
			WHERE A."DocEntry"=:par1;
	ELSE IF :DTYPE='BOOKINGSHEET_VOLUME_LAYOUT' THEN
			SELECT 
				 A."U_QTY" AS QTY
				,A."U_VOLUMECODE" AS VOLUMECODE 
				,IFNULL(TO_DECIMAL(A."U_GROSSWEIGHT",16,2),0) AS GROSSWEIGHT
			FROM EW_PRD."@VOLUME" AS A 
			WHERE A."DocEntry"=:par1;
	ELSE IF :DTYPE='BOOKINGSHEET_TBOVERSEAFORWARDER_LAYOUT' THEN
			SELECT 
				B."CardName" AS OVERSEAFORWARDERCODE 
			FROM EW_PRD."@TBOVERSEAFORWARDER" AS A 
			LEFT JOIN EW_PRD."OCRD" AS B ON B."CardCode"=A."U_OVERSEAFORWARDERCODE"
			WHERE A."DocEntry"=:par1;
	ELSE IF :DTYPE='BOOKINGSHEET_TBTRUCKTYPEROW_LAYOUT' THEN
			SELECT 
				--
				 TO_VARCHAR(TO_DECIMAL(A."U_QTY",3,0)) AS QTY 
				,A."U_TRUCKTYPE" AS TRUCKTYPECODE
				,IFNULL(TO_DECIMAL(A."U_GROSSWEIGHT",16,2),0) AS GROSSWEIGHT
			FROM EW_PRD."@TBTRUCKTYPEROW" AS A 
			WHERE A."DocEntry"=:par1;
	ELSE IF :DTYPE='BOOKINGSHEET_THAIBORDER_LAYOUT' THEN
			SELECT 
				B."Name" AS THAIBORDER 
			FROM EW_PRD."@THAIBORDER" AS A 
			LEFT JOIN EW_PRD."@TBTHAIBORDER" AS B ON A."U_ThaiBorder"=B."Code"
			WHERE A."DocEntry"=:par1;
	ELSE IF :DTYPE='SALEQUOTATIONNEWLAYOUT_HEADER' THEN
			SELECT 
				 A."CardName" AS "CUSTOMERNAME"
				,A."DocDate" AS "DATE" 
				,A."NumAtCard" AS "NumAtCard"
				,B."SlpName" AS "SALENAME"
				,A."DocDueDate" AS "DocDueDate"
				,A."U_ORIGIN" AS "ORIGIN"
				,A."U_DESTINATION" AS "DESTINATION"
				,C."descript"||' - '||CC."descript" AS "ROUTE"
				,A."U_ATTN" AS ATTN
				,A."U_TEL" AS PHONE
				,A."U_EMAIL" AS EMAIL
			FROM EW_PRD."OQUT" AS A 
			LEFT JOIN EW_PRD."OSLP" AS B ON A."SlpCode"=B."SlpCode"
			LEFT JOIN EW_PRD."OTER" AS C ON C."territryID"=A."U_ORIGIN" --ORIGIN
			LEFT JOIN EW_PRD."OTER" AS CC ON CC."territryID"=A."U_DESTINATION" --DESTINATION
			WHERE "DocEntry"=:par1;
	ELSE IF :DTYPE='SALEQUOTATIONNEWLAYOUT_DETAIL' THEN
			SELECT 
				A."LineNum"+1 AS "LINENUMBER",
				A."Dscription" AS "ITEMNAME",
				TO_DECIMAL(A."LineTotal",16,2) AS "TOTAL",
				A."U_Remark" AS "REMARK"
			FROM EW_PRD."QUT1" AS A 
			WHERE "DocEntry"=:par1;
	ELSE IF :DTYPE='TruckWayBill' THEN
		SELECT 
			(SELECT   
				STRING_AGG(B."U_SHIPPER"||' - '||(SELECT 
						STRING_AGG(IFNULL(T0."Address",'')
						||IFNULL(T0."Address2",'')
						||IFNULL(T0."Address3",'')
						||','||T1."Name") AS ADDRESS1
				  		FROM EW_PRD."CRD1" AS T0 
				  		LEFT JOIN EW_PRD."OCRY" AS T1 ON T1."Code"=T0."Country" 
				  		WHERE T0."CardCode"=B."U_SHIPPER")||', ')
			FROM EW_PRD."@BOOKINGSHEET" AS A
			LEFT JOIN EW_PRD."@TBSHIPPER" AS B ON A."DocEntry"=B."DocEntry"
			WHERE A."U_CONFIRMBOOKINGSHEETID"=T0."DocEntry") AS Shipper
			,(SELECT   
				STRING_AGG(B."U_CONSIGNEE"||' - '||(SELECT 
						STRING_AGG(IFNULL(T0."Address",'')
						||IFNULL(T0."Address2",'')
						||IFNULL(T0."Address3",'')
						||','||T1."Name") AS ADDRESS1
				  		FROM EW_PRD."CRD1" AS T0 
				  		LEFT JOIN EW_PRD."OCRY" AS T1 ON T1."Code"=T0."Country" 
				  		WHERE T0."CardCode"=B."U_CONSIGNEE")||', ')
			FROM EW_PRD."@BOOKINGSHEET" AS A
			LEFT JOIN EW_PRD."@TBCONSIGNEE" AS B ON A."DocEntry"=B."DocEntry"
			WHERE A."U_CONFIRMBOOKINGSHEETID"=T0."DocEntry") AS Consignee
			,(SELECT   
				STRING_AGG(C."Name"||','||C."U_COUNTRY"||' ')
			FROM EW_PRD."@BOOKINGSHEET" AS A
			LEFT JOIN EW_PRD."@PLACEOFDELIVERY" AS B ON A."DocEntry"=B."DocEntry"
			LEFT JOIN EW_PRD."@TBPLACEOFDELIVERY" AS C ON C."Code"=B."U_PLACEDELIVERY"
			WHERE A."U_CONFIRMBOOKINGSHEETID"=T0."DocEntry") AS PortOfDestination
			,(SELECT   
				STRING_AGG(C."Name"||','||C."U_COUNTRY"||' ')
			FROM EW_PRD."@BOOKINGSHEET" AS A
			LEFT JOIN EW_PRD."@PLACEOFLOADING" AS B ON A."DocEntry"=B."DocEntry"
			LEFT JOIN EW_PRD."@TBPLACEOFDELIVERY" AS C ON C."Code"=B."U_PLACELOADING"
			WHERE A."U_CONFIRMBOOKINGSHEETID"=T0."DocEntry") AS PortOfLoading
			,(SELECT   
				STRING_AGG('Thai Truck No. '|| B."U_TRUCKCODE" ||' Container No. '|| B."U_CONTAINERNO" || ', ')
			FROM EW_PRD."@CONFIRMBOOKINGSHEET" AS A
			LEFT JOIN EW_PRD."@TRUCKINFORMATION" AS B ON A."DocEntry"=B."DocEntry"
			WHERE A."DocEntry"=T0."DocEntry") AS ListContainer
			,T1."U_EWSeries"||T1."U_JOBNO" AS TruckWayBillNo
			,TO_VARCHAR(T1."U_BOOKINGDATE",'DD-MONTH-YYYY') AS BookingDate
		FROM EW_PRD."@CONFIRMBOOKINGSHEET" AS T0
		LEFT JOIN EW_PRD."@BOOKINGSHEET" AS T1 ON T0."U_BOOKINGID"=T1."DocEntry"
		WHERE T0."DocEntry"=:par1;
	--ConfirmBookingLayout
	ELSE IF :DTYPE='BookingSheetInformation' THEN
		SELECT 
			 B."Name" AS JOBTYPE
			,C."descript"||' - '|| CC."descript" AS ROUTE
			,D."SlpName" AS SALENAME
			,A."U_EWSeries"||A."U_JOBNO" AS JOBNO
			,E."ListName" AS PRICELIST
			,A."Remark" AS REMARK
			,AA."DocEntry" AS DOCENTRY
			,F."firstName" || ' ' || F."lastName" AS USERNAME
			,TO_VARCHAR(A."U_LOADINGDATE",'DD-MONTH-YYYY') AS LOADINGDATE
			,A."U_SPECIALREQUEST" SPECIALREQUEST
		FROM EW_PRD."@BOOKINGSHEET" AS A
		LEFT JOIN EW_PRD."@CONFIRMBOOKINGSHEET" AS AA ON AA."DocEntry"=:par1
		LEFT JOIN EW_PRD."@TBJOBTYPE" AS B ON A."U_IMPORTTYPE"=B."Code"
		LEFT JOIN EW_PRD."OTER" AS C ON C."territryID"=A."U_ORIGIN" --ORIGIN
		LEFT JOIN EW_PRD."OTER" AS CC ON CC."territryID"=A."U_DESTINATION" --DESTINATION
		LEFT JOIN EW_PRD."OSLP" AS D ON D."SlpCode"=A."U_SALEEMPLOYEE"
		LEFT JOIN EW_PRD."OPLN" AS E ON E."ListNum"=AA."U_PRICELIST"
		LEFT JOIN EW_PRD."OHEM" AS F ON F."userId"=A."U_UserCreate"
		WHERE A."U_CONFIRMBOOKINGSHEETID"=:par1;
	ELSE IF :DTYPE='GetBorderBookingSheet' THEN
		SELECT 
			 C."Code" AS CODE
			,C."Name" AS NAME
		FROM EW_PRD."@BOOKINGSHEET" AS A
		LEFT JOIN EW_PRD."@THAIBORDER" AS B ON A."DocEntry"=B."DocEntry"
		LEFT JOIN EW_PRD."@TBTHAIBORDER" AS C ON C."Code"=B."U_ThaiBorder"
		WHERE A."U_CONFIRMBOOKINGSHEETID"=:par1;
	ELSE IF :DTYPE='PLACEOFLOADINGConfirmLayout' THEN
		SELECT 
			B."Name"||', '||B."U_COUNTRY" AS PLACELOADING
		FROM EW_PRD."@PLACEOFLOADING" AS A 
		LEFT JOIN EW_PRD."@TBPLACEOFLOADING" AS B ON B."Code"=A."U_PLACELOADING"
		WHERE A."DocEntry"=:par1;
	ELSE IF :DTYPE='PLACEOFDELIVERYConfirmLayout' THEN
		SELECT 
			B."Name"||', '||B."U_COUNTRY" AS PLACEOFDELIVERY 
		FROM EW_PRD."@PLACEOFDELIVERY" AS A 
		LEFT JOIN EW_PRD."@TBPLACEOFDELIVERY" AS B ON B."Code"=A."U_PLACEDELIVERY"
		WHERE A."DocEntry"=:par1;
	ELSE IF :DTYPE='SHIPPERConfirmLayout' THEN
		SELECT 
			B."CardName" AS SHIPPER 
		FROM EW_PRD."@TBSHIPPER" AS A 
		LEFT JOIN EW_PRD."OCRD" AS B ON B."CardCode"=A."U_SHIPPER"
		WHERE A."DocEntry"=:par1;
	ELSE IF :DTYPE='CONSIGNEEConfirmLayout' THEN
		SELECT 
			B."CardName" AS CONSIGNEE 
		FROM EW_PRD."@TBCONSIGNEE" AS A 
		LEFT JOIN EW_PRD."OCRD" AS B ON B."CardCode"=A."U_CONSIGNEE"
		WHERE A."DocEntry"=:par1;
	ELSE IF :DTYPE='GetListOfContainerInformation' THEN
		SELECT 
			 A."U_TYPE" AS "TYPE"
			,A."U_CONTAINERTYPE" AS CONTAINERTYPE
			,A."U_CONTAINERNO" AS CONTAINERNO
			,A."U_OWNER" AS OWNER
			,A."U_GROSSWEIGHT" AS GROSSWEIGHT
			,A."U_YARD" AS YARD
			,A."U_FCL_LCL" AS FCL_LCL
			,A."U_LOLO_UNLOADING" AS LOLO_UNLOADING
			,B."Location" AS TRUCKPROVINCE
			,A."U_TRUCKPLATENO" AS TRUCKPLATENO
			,A."U_TRUCKTYPE" AS TRUCKTYPE
			,A."U_BRAND" AS BRAND
			,A."U_COLOR" AS COLOR
			,A."U_TRAILERPROVINCE" AS TRAILERPROVINCE
			,A."U_TRAILERPLATE" AS TRAILERPLATE
			,A."U_TRAILERTYPE" AS TRAILERTYPE
			,C."firstName" ||' '|| C."lastName" AS DriverName1
			,C."mobile" AS TPNO1
			,C."govID" AS IDCARD1
			,C."U_DriverID" AS DRIVERLICENSE1
			,CC."firstName" ||' '|| C."lastName" AS DriverName2
			,CC."mobile" AS TPNO2
			,CC."govID" AS IDCARD2
			,CC."U_DriverID" AS DRIVERLICENSE2
			,A."U_VENDORCODE" AS VENDOR
			,A."U_TRUCKCOSTTHB" AS TRUCKCOSTTHB
			,A."U_SEALNO1" AS SEALNO1
			,A."U_SEALNO2" AS SEALNO2
		FROM EW_PRD."@TRUCKINFORMATION" AS A 
		LEFT JOIN EW_PRD."OLCT" AS B ON B."Code"=A."U_TRUCKPROVINCE"
		LEFT JOIN EW_PRD."OHEM" AS C ON C."empID"=A."U_DRIVER1"
		LEFT JOIN EW_PRD."OHEM" AS CC ON CC."empID"=A."U_DRIVER2"
			WHERE A."DocEntry"=:par1;
	ELSE IF :DTYPE='ListOfPurchaseRequestConfirmLayout' THEN
		SELECT 
			 B."NumAtCard" AS REFNO
			,D."NAME" AS PROJECTMANAGEMENT
			,F."U_NAME" AS ISSUEBY
			,B."DocDate" AS ISSUEDATE
			,E."CardName" AS VendorName
			,B."DocDueDate" AS DUEDATE
			,0 AS THBAMOUNT
			,B."DocTotal" AS GRANDTOTAL
			,E."DflAccount" AS BANKACCOUNT
			,E."DflBranch" AS BRANCH	  
			,(SELECT "OCRY"."Name" FROM EW_PRD."OCRY" WHERE "OCRY"."Code"=E."BankCountr") AS BANKCOUNTRY
			,(SELECT "ODSC"."BankName" FROM EW_PRD."ODSC" WHERE "ODSC"."BankCode"=E."BankCode") AS BANKNAME
			,E."DflSwift" AS SWIFTCODE
			,B."Comments" AS "COMMENT"
			,G."ListName" AS PRICELISTNAME
		FROM EW_PRD."@TBPURCHASEREQUEST" AS A 
		LEFT JOIN EW_PRD."ORDR" AS B ON B."DocEntry"=A."U_DOCENTRY"
		LEFT JOIN EW_PRD."@CONFIRMBOOKINGSHEET" AS C ON C."DocEntry"=A."DocEntry"
		LEFT JOIN EW_PRD."OPLN" AS G ON G."ListNum"=C."U_PRICELIST"
		LEFT JOIN EW_PRD."OUSR" AS F ON F."USERID"=C."U_CreateUser"
		LEFT JOIN EW_PRD."OPMG" AS D ON D."AbsEntry"=C."U_PROJECTMANAGEMENTID"
		LEFT JOIN EW_PRD."OCRD" AS E ON E."CardCode"=(SELECT 
														DISTINCT E0."LineVendor" 
														FROM EW_PRD."PRQ1" AS E0 
														WHERE E0."BaseEntry"=B."DocEntry" 
														  	AND E0."BaseType"='17')
		WHERE A."DocEntry"=:par1;
	ELSE IF :DTYPE='ListOfPurchaseRequestLineConfirmLayout' THEN
		SELECT 
			 E0."Dscription" AS DESCRIPTION
			,E0."UomCode" AS SERVICETYPE
			,E0."U_ORIGIN" AS ORIGIN
			,E0."U_DESTINATION" AS DESTINATION
			,E0."LineTotal" AS AMOUNT 
		FROM EW_PRD."@TBPURCHASEREQUEST" AS A
		LEFT JOIN EW_PRD."PRQ1" AS E0 ON E0."BaseEntry"=A."U_DOCENTRY" 
		WHERE A."DocEntry"=:par1 AND E0."BaseType"='17';
	ELSE IF :DTYPE='GetDetailAdvancePaymentByDocEntry' THEN
		SELECT 
			 A."U_NumAtCard" AS DOCNUM
			,A."DocEntry" AS DOCENTRY
			,CASE WHEN TO_VARCHAR(A."U_Project")='0' THEN '' ELSE E."NAME" END AS PROJECTNUMBER
			,TO_VARCHAR(A."U_IssueDate",'dd-mm-YYYY') AS ISSUEDATE
			,TO_VARCHAR(A."U_DueDate",'dd-mm-YYYY') AS DUEDATE
			,A."U_VendorCode" AS VENDORCODE
			,B."CardName" AS VENDORNAME
			,D."ChkName" AS CURRENCY
			,A."U_UserID" AS EMPLOYEEID
			,C."firstName" ||' '|| C."lastName" AS EMPLOYEENAME
			,TO_DECIMAL(A."U_Amount",3,2) AS AMOUNT
			,TO_DECIMAL(A."U_AmountTHB",3,2) AS AMOUNTTHB
			,A."Remark" AS REMARKS
			,B."DflAccount" AS BANKACCOUNT
			,B."DflBranch" AS BRANCH	  
			,(SELECT "OCRY"."Name" FROM EW_PRD."OCRY" WHERE "OCRY"."Code"=B."BankCountr") AS BANKCOUNTRY
			,(SELECT "ODSC"."BankName" FROM EW_PRD."ODSC" WHERE "ODSC"."BankCode"=B."BankCode") AS BANKNAME
			,B."DflSwift" AS SWIFTCODE	
		FROM EW_PRD."@ADVANCEPAYMENT" AS A
		LEFT JOIN EW_PRD."OCRD" AS B ON A."U_VendorCode"=B."CardCode"
		LEFT JOIN EW_PRD."OHEM" AS C ON A."U_UserID"=C."empID"
		LEFT JOIN EW_PRD."OCRN" AS D ON A."U_CurrencyType"=D."CurrCode"
		LEFT JOIN EW_PRD."OPMG" AS E ON E."AbsEntry"=A."U_Project"
		WHERE A."DocEntry"=:par1;
	ELSE IF :DTYPE='GetDetailAdvancePaymentByDocEntryLines' THEN
		SELECT 
			 A."U_ItemCode" AS ITEMCODE
			,B."ItemName" AS ITEMNAME
			,A."U_Qty" AS QTY
			,TO_DECIMAL(A."U_Price",3,2) AS PRICE
			,A."U_Origin"||'-'|| A."U_Destination" AS ORIGIN
			,TO_DECIMAL(A."U_Price",3,2) AS AMOUNT
			,A."U_Remarks" AS REMARKS
			,(SELECT "OUOM"."UomCode" FROM EW_PRD."OUOM" WHERE "OUOM"."UomEntry"=B."UgpEntry") AS SERVICETYPE
		FROM EW_PRD."@ADVANCEPAYMENTROW" AS A
		LEFT JOIN EW_PRD."OITM" AS B ON A."U_ItemCode"=B."ItemCode"
		WHERE A."DocEntry"=:par1;
	ELSE IF :DTYPE='GetPLACEOFLOADING' THEN
		SELECT 
			B."Name"||', '||B."U_COUNTRY" AS PLACELOADING
		FROM EW_PRD."@BOOKINGSHEET" AS AA
		LEFT JOIN EW_PRD."@PLACEOFLOADING" AS A ON A."DocEntry"=AA."DocEntry"
		LEFT JOIN EW_PRD."@TBPLACEOFLOADING" AS B ON B."Code"=A."U_PLACELOADING"			
		WHERE AA."U_CONFIRMBOOKINGSHEETID"=:par1;
	ELSE IF	:DTYPE='GetSHIPPER' THEN
		SELECT 
			B."CardName" AS SHIPPER 
		FROM EW_PRD."@BOOKINGSHEET" AS AA
		LEFT JOIN EW_PRD."@TBSHIPPER" AS A ON A."DocEntry"=AA."DocEntry"
		LEFT JOIN EW_PRD."OCRD" AS B ON B."CardCode"=A."U_SHIPPER"
		WHERE AA."U_CONFIRMBOOKINGSHEETID"=:par1;
	ELSE IF	:DTYPE='GetPLACEOFDELIVERY' THEN
		SELECT 
			B."Name"||', '||B."U_COUNTRY" AS PLACEOFDELIVERY 
		FROM EW_PRD."@BOOKINGSHEET" AS AA
		LEFT JOIN EW_PRD."@PLACEOFDELIVERY" AS A ON AA."DocEntry"=A."DocEntry"
		LEFT JOIN EW_PRD."@TBPLACEOFDELIVERY" AS B ON B."Code"=A."U_PLACEDELIVERY"
		WHERE AA."U_CONFIRMBOOKINGSHEETID"=:par1;
	ELSE IF	:DTYPE='GetCONSIGNEE' THEN
		SELECT 
			B."CardName" AS CONSIGNEE 
		FROM EW_PRD."@BOOKINGSHEET" AS AA
		LEFT JOIN EW_PRD."@TBCONSIGNEE" AS A ON AA."DocEntry"=A."DocEntry"
		LEFT JOIN EW_PRD."OCRD" AS B ON B."CardCode"=A."U_CONSIGNEE"
		WHERE AA."U_CONFIRMBOOKINGSHEETID"=:par1;
	ELSE IF :DTYPE='GetListCommodities' THEN
		SELECT 
			A."U_INVOICE" AS INVOICE
		FROM EW_PRD."@COMMODITY" AS A WHERE A."DocEntry"=:par1;
	ELSE IF :DTYPE='GetVolumeBookingSheetByDocEntry' THEN
		SELECT 
			 A."U_QTY" AS QTY
			,B."Code" AS VOLUMECODE
			,B."Name" AS VOLUME
		FROM EW_PRD."@VOLUME" AS A
		LEFT JOIN EW_PRD."@TBVOLUME" AS B ON B."Code"=A."U_VOLUMECODE"
		WHERE A."DocEntry"=:par1;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
END
